name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Build and test
        run: xcodebuild clean build -project Cicerone.xcodeproj -scheme CiceroneTests CODE_SIGNING_REQUIRED=NO test | xcpretty

      - name: Archive the app
        run: xcodebuild -project Cicerone.xcodeproj -scheme CiceroneTests -archivePath ${{ github.workspace }}/build/Cicerone.xcarchive archive

      - name: Export the .app file
        run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Cicerone.xcarchive -exportPath ${{ github.workspace }}/build -exportOptionsPlist ExportOptions.plist

      - name: Upload .app file
        uses: actions/upload-artifact@v3
        with:
          name: Cicerone-App
          path: ${{ github.workspace }}/build/Cicerone.app
